# Generated by Django 3.1.5 on 2021-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='back_c',
            field=models.CharField(default='antiquewhite', max_length=50, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='font_c',
            field=models.CharField(default='black', max_length=50, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='info',
            field=models.TextField(default='-', verbose_name='Краткая информация'),
        ),
    ]
